export const GameConfig = {

    GRID_ROWS: 8,
    GRID_COLS: 8,
    TILE_COLOR_COUNT: 5,

    TARGET_SCORE: 1000,
    MAX_MOVES: 25,
    MIN_GROUP_SIZE: 2,
    MAX_SHUFFLES: 3,

    BASE_POINTS_PER_TILE: 10,

    SUPER_TILE_THRESHOLD: 5,
    SUPER_ROW_CLEAR_MIN: 5,
    SUPER_COL_CLEAR_MIN: 7,
    SUPER_RADIUS_BOMB_MIN: 9,
    SUPER_FIELD_CLEAR_MIN: 12,
    SUPER_BOMB_RADIUS: 2,

    BOMB_RADIUS: 2,
    INITIAL_BOMB_COUNT: 3,
    INITIAL_TELEPORT_COUNT: 3,

    TILE_WIDTH: 100,
    TILE_HEIGHT: 112,
    CELL_GAP: 4,

    DESTROY_DURATION: 0.20,
    FALL_DURATION_PER_CELL: 0.06,
    SPAWN_DURATION: 0.15,
    SWAP_DURATION: 0.25,
    SHUFFLE_HALF_DURATION: 0.20,
    DISMISS_DURATION: 0.20,

    BOMB_WAVE_DELAY_PER_DIST: 0.04,
    BOMB_FLASH_DURATION: 0.10,
    BOMB_SHRINK_DURATION: 0.18,
    BOMB_FLASH_SCALE: 1.45,

    CASCADE_COL_DELAY: 0.07,
    CASCADE_ROW_DELAY: 0.035,
    CASCADE_FALL_DURATION: 0.35,
    CASCADE_START_OFFSET_Y: 400,

    LINE_SWEEP_DELAY_PER_CELL: 0.035,
    LINE_BEAM_EXPAND_DUR: 0.15,
    LINE_BEAM_FADE_DUR: 0.25,
    LINE_STRETCH_DUR: 0.09,
    LINE_SHRINK_DUR: 0.14,
    LINE_BEAM_HEIGHT: 10,

    FIELD_CLEAR_DELAY_PER_DIST: 0.03,
    FIELD_CLEAR_FLASH_DUR: 0.10,
    FIELD_CLEAR_SHRINK_DUR: 0.20,

    SCORE_POPUP_FONT_SIZE: 44,
    SCORE_POPUP_FLOAT_Y: 110,
    SCORE_POPUP_GROW_DURATION: 0.15,
    SCORE_POPUP_FLOAT_DURATION: 0.55,

    SCORE_COUNTER_DURATION: 0.45,

} as const;
